### ISSUE TITLE
Add Azure Integration

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-integrations#156]
Azure is an addition that lives in the main repo. Therefore, the list of tasks is different than regular integrations:

```[tasklist]
### Tasks
- [ ] The code is documented with docstrings and was merged in the `main` branch
- [ ] Docs are published at https://docs.haystack.deepset.ai/
- [ ] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations
- [ ] There is an example available to demonstrate the feature
- [ ] The feature was announced through social media
```
