### ISSUE TITLE
Move DocumentStores to Integrations

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-integrations#30]
```[tasklist]
### Tasks
- [ ] Prepare a guideline on "Creating a Document Store" https://github.com/deepset-ai/devrel-board/issues/73 
- [ ] Contact providers for the ownership
- [ ] Collaboration of core&devrel for creating integrations
- [ ] Start the deprecation process
- [ ] Create a testing package for external document stores https://github.com/deepset-ai/devrel-board/issues/73 
```

**Comment by bilgeyucel** [comment]
Some items in the issue are deprecated but here's what we have done so far:
- We have template repository for 2.0 Document Stores: https://github.com/deepset-ai/document-store/tree/main
- We are in touch with the providers
- All existing DocumentStores has a page on Haystack Integrations
    - The behavior will be the same for 2.0 Document Stores
